spring:
  freemarker:
    template-loader-path:
     - classpath:/templates/
     - classpath:/
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev
server:
  port: 10001

