server:
  port: 6604
spring:
  application:
    name: gateway-service
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
#      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
#          enabled: true
      routes:
      - id: 163                     #网关路由到网易官网
        uri: http://www.163.com/
        predicates:
          - Path=/163
      - id: user
        uri: lb://feign-service
        predicates:
          - Path= /user/**
        filters:
          - StripPrefix=1
          - name: Hystrix
            args:
              name: fallbackcmd
              fallbackUri: forward:/fallback?lb=feign-service
eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
  #服务刷新时间配置，每隔这个时间会主动心跳一次
  #默认30s
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      my-metadata: test
  #eureka client刷新本地缓存时间
  #默认30s
  client:
    registryFetchIntervalSeconds: 5
    #最好每个实例不同顺序，按照离自己最近的Eureka地址放到最前面
    serviceUrl:
#      defaultZone: http://datawin:1q2w3e4r@192.168.2.169:5555/eureka/
      defaultZone: http://localhost:8761/eureka/

#springboot2.0. 的配置项为：
#actuator端口
#management:
#  server:
#    port: 9001
#  endpoints:
#    web:
#   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
#      exposure:
#        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
