server:
  port: 10003
spring:
  application:
    name: eureka-ribbon-client-hystrix
#TIME OUT 设置
eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
  #服务刷新时间配置，每隔这个时间会主动心跳一次
  #默认30s
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      my-metadata: test
  #eureka client刷新本地缓存时间
  #默认30s
  client:
    registryFetchIntervalSeconds: 5
    #最好每个实例不同顺序，按照离自己最近的Eureka地址放到最前面
    serviceUrl:
#      defaultZone: http://datawin:1q2w3e4r@192.168.2.169:5555/eureka/
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true