server:
  port: 10001
spring:
  application:
    name: feign
#TIME OUT 设置
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 15
  #服务刷新时间配置，每隔这个时间会主动心跳一次
  #默认30s
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      my-metadata: test
  #eureka client刷新本地缓存时间
  #默认30s
  client:
    registryFetchIntervalSeconds: 5
    #最好每个实例不同顺序，按照离自己最近的Eureka地址放到最前面
    serviceUrl:
#      defaultZone: http://datawin:1q2w3e4r@192.168.2.169:5555/eureka/
      defaultZone: http://localhost:8761/eureka/
#springboot2.0. 的配置项为：
#actuator端口
management:
  server:
    port: 9001
  endpoints:
    web:
   #   base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
      exposure:
        include: '*'  #开放所有页面节点  默认只开启了health、info两个节点