spring:
  application:
    name: mongo-multi
  data:
    mongodb:
       ai:
          hosts:
            - 61.160.248.132
          ports:
            - 50000
          username: admin
          password: '9ol*IK&UJ6yh'
          database: cloud_call
          authentication-database: admin
          connections-per-host: 20
          min-connections-per-host: 20
