spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    #数据库索引
    database: 0
    host: localhost
    port: 6379
    password: '`1qazx'
    lettuce: # NOT JEDIS
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    #连接超时时间
    timeout: 10000